possible buffer overflow.
LibreDWG/libredwg pull request #419
Opened 2022-02-28 11:09 UTC by ihsinme

at function `dwg_add_XRECORD_handle` on line 25239, an attempt is made to write 24 bytes into an 8-byte array.
maybe I'm wrong, but this is not what you wanted.
structure `Dwg_Handle` corresponds to 24 bytes on an x64 system.
and this write can lead to unexpected results, such as violation of data integrity and even accessibility of the program.

you may have asked to fill in field `value.h`

2022-03-01 11:51 UTC, rurban approved these changes
hdl and h are the same, but the sizeof is a good catch for 32bit archs.

2022-03-01 11:54 UTC, rurban reviewed
Still have to think about that though...

2022-03-01 12:05 UTC, rurban requested changes

2022-03-01 12:05 UTC, rurban commented on src/dwg_api.c
> -  memcpy (rbuf->value.hdl, &hdl, sizeof (Dwg_Handle));
Looks like &rbuf->value.hdl is needed here

2022-03-01 12:05 UTC, rurban commented on src/dwg_api.c
> -  _obj->xdata_size += 10; // 2 + 8
No, this size is hardcoded in the specs

2022-03-03 06:52 UTC, ihsinme commented
sorry, i'm confused.
what I should do?

2022-03-03 14:09 UTC, rurban commented
I think I've fixed the problem already in the smoke/devel branch, but had no time yet to verify it. Friday earliest

2022-03-05 19:06 UTC, rurban commented
I've changed it differently, but thanks for the good find

2022-03-05 19:06 UTC, closed without merging