Export dwg_add_ATTDEF function
LibreDWG/libredwg pull request #613
Opened 2023-01-28 13:28 UTC by michal-josef-spacek

attdef is regular entity, independent on other

2023-01-31 05:13 UTC, rurban requested changes
See dwg_api.h on dwg_add_Attribute:

  This adds the ATTRIB and ENDBLK to the insert,
  and the ATTDEF and ENDBLK to the block, if missing.

Letting the user all do this will be too complicated.

2023-01-31 06:59 UTC, michal-josef-spacek commented on examples/dwgadd.example
> -attribute 8 0 "prompt" (0.0 1.0 0.0) "tag" "text"
Yes, we need to add an attrib.

The question is, does dwg_add_Attribute make sense?

2023-01-31 07:54 UTC, michal-josef-spacek commented on examples/dwgadd.example
> -attribute 8 0 "prompt" (0.0 1.0 0.0) "tag" "text"
Hm, I need to look more.
In AutoCAD script is an attdef and insert (with values for attrib based on attdef)

2023-02-01 10:48 UTC, rurban commented
Merged with various fixups

2023-02-01 10:48 UTC, closed without merging