Fix leader hook line flag
LibreDWG/libredwg pull request #842
Opened 2023-09-18 17:48 UTC by gentilinigm

This includes a calculation based on how autocad displays it, it remains unclear if the flag is actually stored somewhere.

From:
https://help.autodesk.com/view/ACDMAC/2018/ENU/index.html?guid=GUID-BC466DEE-ACD8-419A-B017-AB3065336AD7
https://documentation.help/AutoCAD-ActiveX-AAG/WS1a9193826455f5ff1a32d8d10ebc6b7ccc-6b57.htm

Hook lines appears last leader line segment is at an angle greater than 15 Degrees from horizontal. 
If the leader has no annotation or a spline path (?), it has no hook line.

2023-09-20 07:44 UTC, rurban requested changes
please squash them into 1 commit
didn't you add an angle helper (atan)?

2023-09-20 10:02 UTC, gentilinigm commented
>please squash them into 1 commit

Done!

> didn't you add an angle helper (atan)?

Yes, Ive used atan2: `angleR = atan2(pt1.y - pt2.y, pt1.x - pt2.x);`

2023-09-21 08:52 UTC, rurban requested changes
We also need to calculate the hookline_on flag for the ENCODER, so better move the calculation to a helper function.

2023-09-21 09:48 UTC, gentilinigm commented
Sure I can move the calculation.

But how does the ENCODER work in this case exactly? Is it just a check?
I mean, the hook line status doesn't really tell us much about the other values.

2023-09-21 11:12 UTC, rurban commented
The problem is that we cannot always be sure that the user did set the hookline_flag correctly. We should set it according to the angle of the last 2 pts, same as in the DECODER.

2023-09-21 14:51 UTC, gentilinigm commented
I've made a few commits, isn't the hook line flag encoding DXF only though?

2023-09-21 19:35 UTC, rurban commented
I"ve rewritten it a bit, but kept your logic. Thanks!

2023-09-21 19:35 UTC, closed without merging