Fix 2ndheader encoding
LibreDWG/libredwg pull request #865
Opened 2023-11-09 21:30 UTC by michal-josef-spacek

2023-11-10 07:55 UTC, rurban commented
Yes, it fixed a few json-check oda errors.

2023-11-10 09:53 UTC, rurban commented
We should store the SECTION_2NDHEADER_R13_SIZE part in some junk field

2023-11-11 08:37 UTC, michal-josef-spacek commented
I added info about structure to log.

2023-11-12 18:25 UTC, rurban requested changes

2023-11-12 18:26 UTC, rurban requested changes

2023-11-12 18:26 UTC, rurban commented on include/dwg.h
> +typedef enum DWG_SECTION_SIZE_R13
I'd prefer this as define, not enum.

2023-11-12 18:26 UTC, rurban commented on include/dwg.h
> +  BITCODE_RC before_sentinel[53];
and use the define here

2023-11-13 21:26 UTC, michal-josef-spacek commented on src/encode.c
> +      encode_patch_RLsize (dat, pvzadr);
My code is totally wrong

2023-11-13 21:26 UTC, michal-josef-spacek commented on include/dwg.h
> +typedef enum DWG_SECTION_SIZE_R13
My code is totally wrong

2023-11-13 21:26 UTC, michal-josef-spacek commented on include/dwg.h
> +  BITCODE_RC before_sentinel[53];
My code is totally wrong

2023-11-14 05:48 UTC, rurban approved these changes

2023-11-14 06:46 UTC, rurban requested changes
see my work/r13-objfreespace

2023-11-14 06:46 UTC, rurban commented on src/encode.c
>        assert (dat->byte);
add encode_objfreespace here

2023-11-14 06:46 UTC, rurban commented on src/decode.c
> +      && dwg->header.section[SECTION_OBJFREESPACE_R13].address != 0)
address is usually 0. rather search for the sentinel, and check if object_end equals dat->byte - 53. if there's room for this section before 2ndheader

2023-11-24 07:42 UTC, closed without merging

2023-11-24 07:42 UTC, rurban commented
Merged with fixes